
Path to store results already exists
self.partnames :  ['head', 'neck', 'torso', 'legs', 'tail', 'background']
prompts :  [' the head of the cat.', ' the neck of the cat.', ' the torso of the cat.', ' the legs of the cat.', ' the tail of the cat.', ' the background of the cat.']
model device :  cuda
self.prompts : torch.Size([6, 77])
self.prompts : torch.Size([6, 1024])
self.prompts rquires grad :  <built-in method requires_grad_ of Tensor object at 0x7ff7e1831680>
Loading checkpoint './last_model'
Loaded model is for epoch 9
Loaded checkpoint './last_model'
Length of Train dataset : 646 and Test dataset : 35
Length of Train loader : 65 and Test loader : 4
(array([1, 3]), array([  3257, 498503]))
(array([1, 3]), array([  3536, 498224]))
(array([1, 3]), array([  3116, 498644]))
(array([1, 3]), array([  1830, 249050]))
Done testing
average loss :  1.74277725815773
(array([1, 3]), array([  3257, 498503]))
(array([1, 3]), array([  3536, 498224]))
(array([1, 3]), array([  3116, 498644]))
(array([1, 3]), array([  1830, 249050]))
Done testing
average loss :  1.7427773177623749
Traceback (most recent call last):
  File "/ssd-scratch/harsh21122/ContextPromptPart/test.py", line 118, in <module>
    wandb.save(os.path.join(args.result_dir), '*.png')
  File "/home/harsh21122/.conda/envs/part/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 245, in wrapper
    return func(self, *args, **kwargs)
  File "/home/harsh21122/.conda/envs/part/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1614, in save
    return self._save(glob_str, base_path, policy)
  File "/home/harsh21122/.conda/envs/part/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1644, in _save
    raise ValueError("globs can't walk above base_path")
ValueError: globs can't walk above base_path